const fs = require('fs');
const path = require('path');

// Default local fallback
let apiBaseUrl = 'http://localhost:8080/api/tasks';

// 1. Try to read from local .env file if it exists
try {
  const envPath = path.resolve(__dirname, '.env');
  if (fs.existsSync(envPath)) {
    const envContent = fs.readFileSync(envPath, 'utf8');
    const match = envContent.match(/^API_BASE_URL\s*=\s*(.*)$/m);
    if (match && match[1]) {
      apiBaseUrl = match[1].trim().replace(/^['"]|['"]$/g, '');
    }
  }
} catch (err) {
  console.warn('Could not read .env file, using defaults.');
}

// 2. Override with system/environment variables (e.g. injected on Netlify build)
if (process.env.API_BASE_URL) {
  apiBaseUrl = process.env.API_BASE_URL;
}

const configContent = `// Automatically generated by prebuild.js. Do not edit directly.
export const API_BASE_URL = '${apiBaseUrl}';
`;

fs.writeFileSync(path.resolve(__dirname, 'src/app/config.ts'), configContent);
console.log(`Prebuild: Configured API_BASE_URL as -> ${apiBaseUrl}`);
